### ISSUE TITLE
Hooks usage error

### ISSUE THREAD

**Issue by PuruVJ** [Silind-Software/restater#1]
Hi

I've been getting this error when trying to use restater hook
![image](https://user-images.githubusercontent.com/47742487/100359649-d921fc00-301d-11eb-8658-de92c0c6e184.png)

Source: https://github.com/PuruVJ/macos-web/blob/feat/dock-item-component-and-list/src/components/dock/Dock.tsx#L12
The provider is here: https://github.com/PuruVJ/macos-web/blob/feat/dock-item-component-and-list/src/views/desktop/Desktop.tsx#L17

The error is happening only with restater call, as replacing `useStore` with `useState` is working perfectly fine.

I checked if this is the issue: https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react
and downgraded down to 16.14.0 from 17.0.1

Still getting the same error.

Please help

**Comment by SimonHoiberg** [comment]
Hi @PuruVJ :wave: 
Thanks for creating this issue.

Nice catch!
Try using v. 0.0.12.
This issue should be solved now.

**Comment by PuruVJ** [comment]
Wow Really quick response. trying it out.

**Comment by PuruVJ** [comment]
Works perfectly. Thank you for resolving so fast.

**Comment by PuruVJ** [comment]
Can I ask what was the exact issue?

**Comment by PuruVJ** [comment]
Never mind. Found it https://github.com/SimonHoiberg/restater/commit/83926d0a80ecabb007356c262b411f45219b2704
